# fly.toml app configuration file generated for chatapirest on 2023-06-15T09:41:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatapirest"
primary_region = "gdl"

[http_service]
  internal_port = 8088
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
